# Generated by Django 3.0.4 on 2020-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmodels', '0004_auto_20200314_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_deviceinfodetails',
            name='deviceinforelay',
            field=models.CharField(blank=True, help_text='继电器命令前缀，固定最长7', max_length=7, verbose_name='输出命令前缀'),
        ),
    ]
