# Generated by Django 3.0.4 on 2020-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmodels', '0005_iot_deviceinfodetails_deviceinforelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_clientdevice',
            name='clientdevarea',
            field=models.CharField(blank=True, help_text='客户自身对设备所在区域的划分', max_length=30, verbose_name='区域划分'),
        ),
        migrations.AddField(
            model_name='iot_clientdevice',
            name='clientdevgroup',
            field=models.CharField(blank=True, help_text='客户自身对设备所在组的划分', max_length=30, verbose_name='分组划分'),
        ),
    ]
